version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nextjs-app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DATABSE_URL=postgres://postgres:postgres@postgres:5432/mydb

volumes:
  pgdata: